# Loggers
logger: "tensorboard"  # Logger to use for logging (e.g., 'wandb' or 'tensorboard')
# Simulation settings
num_rsu: 4  # Number of RSUs (Road Side Units)
num_vehicle: 40  # Total number of vehicles in the simulation
time_step_per_round: 10  # Duration of each round in time steps
num_rounds: 30  # Total number of rounds for the simulation
content_size: 4000000  # Size of content in bytes (4e6)
deadline: 1  # Deadline for content delivery in seconds

# Mobility settings
min_velocity: 5  # Minimum speed of vehicles
max_velocity: 10  # Maximum speed of vehicles
std_velocity: 2.5  # Standard deviation of vehicle speed

# Connection settings
rsu_coverage: 500  # Coverage area of each RSU in meters
rsu_capacity: 100  # Maximum capacity of RSUs
cloud_rate: 10000000.0  # Cloud connection rate (100e6)
fiber_rate: 150000000.0  # Fiber optic connection rate (150e6)
max_connections: 10  # Maximum simultaneous connections

# FL (Federated Learning) settings
num_clusters: 3  # Number of clusters in FL
num_local_epochs: 5  # Number of local training epochs
parallel_update: false  # Whether to use parallel updates or not

# DRL (Deep Reinforcement Learning) settings
episodes: 100  # Number of episodes to run
device: "cuda"  # Device to use for training (e.g., 'cuda' or 'cpu')
train_every: 4 # Frequency of training the agent
batch_size: 32  # Size of training batches
gamma: 0.9  # Discount factor for future rewards
lr: 0.001  # Learning rate
capacity: 10000  # Capacity for training
hidden_dim: 512  # Hidden dimension for the neural network
target_update: 500  # Frequency of target network updates
training_steps: 3000 # Total training steps per episode
epsilon_decay: 0.99995  # Decay rate for exploration
epsilon_min: 0.01  # Minimum value for epsilon
alpha: 1  # Alpha parameter for the algorithm
beta: 0  # Beta parameter for the algorithm
mu: 0  # Mu parameter for the algorithm
